const path = require('path');
const fs = require('fs');
const Export = require('../models/Export');
const Document = require('../models/Document');
const Analysis = require('../models/Analysis');
const Chat = require('../models/Chat');
const StudyMaterial = require('../models/StudyMaterial');
const exportService = require('../services/exportService');
const { logActivity } = require('../middleware/activityLogger');

const generateExport = async (req, res) => {
  try {
    const { documentId, exportType = 'analysis', format = 'pdf', title = 'Nexora AI Report' } = req.body;
    const userId = req.user.id;

    const doc = documentId ? Document.findById(documentId) : null;
    const docName = doc ? doc.originalName : title;

    let contentBlocks = [];
    let rawContent = '';
    let exportTitle = `${title} — ${docName}`;

    if (exportType === 'analysis') {
      const analysis = Analysis.findOne({ documentId, ownerId: userId }) || {
        executiveSummary: 'Document executive analysis generated by Nexora AI.',
        keyPoints: ['Core point 1', 'Core point 2'],
        insights: ['Key insight 1']
      };

      contentBlocks = [
        { heading: 'Executive Summary', text: analysis.executiveSummary },
        { heading: 'Detailed Breakdown', text: analysis.detailedSummary || analysis.simpleSummary },
        { heading: 'Key Strategic Takeaways', list: analysis.keyPoints },
        { heading: 'Document Insights & Facts', list: analysis.insights },
        { heading: 'Recommended Action Items', list: analysis.actionItems }
      ];

      rawContent = `# ${exportTitle}\n\n## Executive Summary\n${analysis.executiveSummary}\n\n## Key Points\n${(analysis.keyPoints || []).map(p => `- ${p}`).join('\n')}\n\n## Insights\n${(analysis.insights || []).map(i => `- ${i}`).join('\n')}`;
    } else if (exportType === 'chat') {
      const chat = Chat.findOne({ documentId, ownerId: userId }) || { messages: [] };
      contentBlocks = (chat.messages || []).map(m => ({
        heading: m.role === 'user' ? 'User Question' : 'Nexora AI Response (Grounded)',
        text: m.content
      }));
      rawContent = (chat.messages || []).map(m => `**${m.role.toUpperCase()}**: ${m.content}`).join('\n\n');
    } else if (exportType === 'study') {
      const study = StudyMaterial.findOne({ documentId, ownerId: userId }) || {};
      contentBlocks = [
        { heading: 'Chapter Summary', text: study.chapterSummary || 'Study summary' },
        { heading: 'High Yield Revision Notes', list: study.revisionNotes || [] },
        { heading: 'Exam Preparation Tips', list: study.examFocusedPoints || [] }
      ];
      rawContent = study.quickRevisionSheet || JSON.stringify(study, null, 2);
    } else {
      contentBlocks = [{ heading: 'Document Report', text: `Nexora AI exported report for ${docName}` }];
      rawContent = `Nexora AI Report: ${docName}`;
    }

    let fileResult;
    const cleanPrefix = `NexoraAI_${exportType}_${docName.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20)}`;

    if (format === 'pdf') {
      fileResult = await exportService.generatePDF(exportTitle, contentBlocks, cleanPrefix);
    } else if (format === 'docx') {
      fileResult = await exportService.generateDOCX(exportTitle, contentBlocks, cleanPrefix);
    } else if (format === 'xlsx' || format === 'csv') {
      const flatData = contentBlocks.map(b => ({
        Section: b.heading,
        Details: b.text || (b.list ? b.list.join('; ') : '')
      }));
      fileResult = await exportService.generateXLSX(flatData, 'NexoraExport', cleanPrefix);
    } else {
      fileResult = await exportService.generateTextFormat(rawContent, format, cleanPrefix);
    }

    const newExport = Export.create({
      ownerId: userId,
      documentId: documentId || null,
      documentName: docName,
      title: exportTitle,
      exportType,
      format,
      fileName: fileResult.fileName,
      filePath: fileResult.filePath
    });

    logActivity(userId, 'EXPORT_DOCUMENT', 'SUCCESS', { exportType, format, fileName: fileResult.fileName }, req.ip);

    return res.json({
      success: true,
      message: 'Export generated successfully.',
      exportRecord: newExport,
      downloadUrl: `/api/exports/download/${newExport._id}`
    });
  } catch (err) {
    console.error('Export error:', err);
    return res.status(500).json({ success: false, message: 'Failed to generate export file.' });
  }
};

const getExports = async (req, res) => {
  try {
    const userId = req.user.id;
    const exportsList = Export.find({ ownerId: userId }).sort({ createdAt: -1 }).exec();
    return res.json({ success: true, exports: exportsList });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Failed to fetch exports.' });
  }
};

const downloadExportFile = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const exportRecord = Export.findById(id);
    if (!exportRecord) {
      return res.status(404).json({ success: false, message: 'Export record not found.' });
    }

    if (exportRecord.ownerId !== userId && req.user.role !== 'SUPER_ADMIN') {
      return res.status(403).json({ success: false, message: 'Unauthorized.' });
    }

    if (!fs.existsSync(exportRecord.filePath)) {
      return res.status(404).json({ success: false, message: 'Export file has expired or was removed from disk.' });
    }

    res.setHeader('Content-Disposition', `attachment; filename="${exportRecord.fileName}"`);
    const fileStream = fs.createReadStream(exportRecord.filePath);
    return fileStream.pipe(res);
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Download failed.' });
  }
};

module.exports = {
  generateExport,
  getExports,
  downloadExportFile
};
